### ISSUE TITLE
Roost Nav Bar

### ISSUE THREAD

**Issue by jwalter26** [COSC481W-2021Fall/capstone-adam-and-the-mod-squad#104]
MAITENENCE ITEM
Roost should be highlighted on sidebar when you are on the Roost page

ACCEPTANCE CRITERIA
Nav bar shows highlighted roost when on that page

TASKS
- Fix styling for base.html - Sara

**Comment by dreaka17** [comment]
Just reopening so Professor Jiang can see this in the link we sent
